//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ComCtrl.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_COMCTRL_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     132
#define IDD_DIALOG2                     133
#define IDD_DIALOG3                     134
#define IDB_BITMAP1                     138
#define IDB_BITMAP2                     139
#define IDB_BITMAP3                     150
#define IDB_BITMAP4                     159
#define IDD_DIALOG4                     160
#define IDD_DIALOG5                     161
#define IDI_ICON1                       162
#define IDB_BITMAP5                     163
#define IDB_BITMAP6                     165
#define IDB_BITMAP7                     166
#define IDB_BITMAP8                     167
#define IDD_DIALOG6                     168
#define IDD_DIALOG7                     169
#define IDD_DIALOG8                     170
#define IDD_DIALOG9                     171
#define IDC_COMBO_BAUDRATE              1001
#define IDC_BTN_OPEN                    1002
#define IDC_EDIT_ADD1                   1003
#define IDC_EDIT_ADD2                   1004
#define IDC_COMBO_COM1                  1005
#define IDC_COMBO_COM2                  1006
#define IDC_EDIT_CT2                    1007
#define IDC_EDIT_CT1                    1008
#define IDC_EDIT_CP1                    1009
#define IDC_EDIT_CP2                    1010
#define IDC_BTN_SEND                    1011
#define IDC_BTN_MANUALSEND              1012
#define IDC_BTN_CLEAR                   1013
#define IDC_LIST_RECV                   1014
#define IDC_LIST_ZT2                    1017
#define IDC_BTN_CHECK                   1019
#define IDC_DATETIMEPICKER1             1020
#define IDC_DATETIMEPICKER2             1021
#define IDC_EDIT_TIME                   1022
#define IDC_BTN_PC                      1024
#define IDC_BTN_EXCEL                   1025
#define IDC_COMBO_CHOICE                1026
#define IDC_STATIC1                     1027
#define IDC_STATIC2                     1028
#define IDC_AUTHOR                      1028
#define IDC_BTN_ZT                      1029
#define IDC_LIST_ZT1                    1030
#define IDC_EDIT_SAVEPATH               1030
#define IDC_LIST2                       1033
#define IDC_TCHART3                     1035
#define IDC_TCHART4                     1036
#define IDC_TCHART1                     1037
#define IDC_TCHART2                     1038
#define IDC_TCHART5                     1039
#define IDC_TITLE                       1039
#define IDC_TCHART6                     1040
#define IDC_TCHART7                     1041
#define IDC_BTN_SAVE                    1045
#define IDC_BTN_CONFIGDATA              1046
#define IDC_STATIC3                     1048
#define IDC_BTN_MO                      1049
#define IDC_BTN_RE                      1050
#define IDC_NAME                        1050
#define IDC_PASSWORD                    1051
#define ID_EDIT_LOG                     1052
#define IDC_LIST1                       1053
#define IDC_COMBO1                      1054
#define IDC_LIST3                       1054
#define IDC_BUTTON1                     1055
#define IDC_BTNPL                       1055
#define IDC_BTN_CHANGE                  1055
#define IDC_SAVE_SET                    1055
#define IDC__START_TEST                 1055
#define IDC_BUTTON2                     1056
#define IDC_BTNPF                       1056
#define IDC_STOP_TEST                   1056
#define IDC_BUTTON3                     1057
#define IDC_BTNV                        1057
#define IDC_BTNI                        1058
#define IDC_BTNT                        1059
#define IDC_CUSTOM_CHART                1060
#define IDC_CHECK1                      1061
#define IDC_EDIT1                       1062
#define IDC_EDIT2                       1063
#define IDC_RADIO1                      1063
#define IDC_EDIT3                       1064
#define IDC_RADIO2                      1064
#define IDC_RADIO3                      1065
#define IDC_TEMP_LABEL                  1066
#define IDC_O2_LABEL                    1067
#define IDC_O2_NO                       1068
#define IDC_TEMP_NO                     1069
#define IDC_PRESSA_LABEL                1070
#define IDC_PRESSA_NO                   1071
#define IDC_PRESSB_LABEL                1072
#define IDC_PRESSB_NO                   1073
#define IDC_PRESSC_LABEL                1074
#define IDC_PRESSC_NO                   1075
#define IDC_BUTTON5                     1077
#define IDC_BUTTON6                     1078
#define IDC_BUTTON7                     1079
#define IDC_BUTTON8                     1080
#define IDC_BUTTON9                     1081
#define IDC_DATETIMEPICKER3             1083
#define IDC_DATETIMEPICKER4             1084
#define IDC_DATA_SEARCH_LABEL           1085
#define IDC_BUTTON4                     1086
#define IDC_AUTHER_ENG                  1087
#define IDC_SAVE                        1088
#define IDC_RESET                       1090
#define IDC_TEMP_SET                    1091
#define IDC_PRESS_SET                   1092
#define IDC_O2_SET                      1093
#define IDC_TEMP_HIGH_SET               1094
#define IDC_PRESS_SET_HIGH              1095
#define IDC_O2_SET_HIGH                 1096
#define IDC_BUTTON11                    1097
#define IDC_BUTTON14                    1101
#define IDC_BUTTON15                    1103
#define IDC_BUTTON13                    1106
#define IDC_CHECK2                      1107
#define IDC_CHECK3                      1108
#define IDC_BUTTON17                    1110
#define IDC_CHECK4                      1112
#define IDC_CHECK5                      1113
#define IDC_CHECK6                      1114

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
